### ISSUE TITLE
A service user cannot post a manual dag

### ISSUE THREAD

**Issue by pchtsp** [baobabsoluciones/corn#70]
Neither can a normal user.

See cornflow/endpoints/dag.py:DAGEndpointManual

It has `ROLES_WITH_ACCESS = [ADMIN_ROLE, SERVICE_ROLE]` But it does accept the request from a `SERVICE_ROLE` user. It does not accept a planner user, I guess. It should allow, at least, the `SERVICE_ROLE` and probably, the `PLANNER_ROLE`.

**Comment by ggsdc** [comment]
Ok so for the service user doesn't work because the service user does not have permission to post in any endpoint:

```
BASE_PERMISSION_ASSIGNATION = [
    (VIEWER_ROLE, GET_ACTION),
    (PLANNER_ROLE, GET_ACTION),
    (PLANNER_ROLE, PATCH_ACTION),
    (PLANNER_ROLE, POST_ACTION),
    (PLANNER_ROLE, PUT_ACTION),
    (PLANNER_ROLE, DELETE_ACTION),
    (ADMIN_ROLE, GET_ACTION),
    (ADMIN_ROLE, PATCH_ACTION),
    (ADMIN_ROLE, POST_ACTION),
    (ADMIN_ROLE, PUT_ACTION),
    (ADMIN_ROLE, DELETE_ACTION),
    (SERVICE_ROLE, GET_ACTION),
    (SERVICE_ROLE, PATCH_ACTION),
    (SERVICE_ROLE, PUT_ACTION),
    (SERVICE_ROLE, DELETE_ACTION),
]
```

I could add an exception in `EXTRA_PERMISSION_ASSIGNATION = [(VIEWER_ROLE, PUT_ACTION, "user-detail")]` and that should fix it. This same exception could be added to the `PLANNER_ROLE`.
